dist: xenial

language: python

matrix:
  include:
    - python: 3.9
    - python: 3.10
    - python: 3.11


cache: pip

branches:
  only:
    - external

install:
  # Install Python script dependencies
  - pip install --upgrade pip setuptools
  - pip install --upgrade -r requirements.txt

script:
  - python -m pytest -v